### ISSUE TITLE
How to make the corresponding bracket highlight obviously?

### ISSUE THREAD

**Issue by keketang** [ajaxorg/ace-builds#165]

**Comment by nightwing** [comment]
Add css rule for `.ace_bracket ` class. For instance:

```css
.ace_bracket {
    border-color: magenta!important;
}
```
